name: publish

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Copy install shell scripts to GitHub Pages branch
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Synchronise shell scripts
      run: |
        OLDSCRIPTS=$(find gh-pages -type f -name "*.sh")

        NEWSCRIPTS=$(find main/install -type f -name "*.sh")

        for SCRIPT in ${OLDSCRIPTS}
        do
          rm "${SCRIPT}"
        done

        for SCRIPT in ${NEWSCRIPTS}
        do
          cp "${SCRIPT}" gh-pages
        done

    - name: Deploy new scripts to GitHub Pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        HASH=$(git -C main rev-parse --short HEAD)

        if ! git -C gh-pages diff-index --quiet HEAD
        then
          git -C gh-pages add -A
          git -C gh-pages commit -m "Deploy Install Scripts: ${HASH}"
          git -C gh-pages push
        fi

  arch-pkg:
    name: Build Arch Linux packages and copy to GitHub Pages branch
    runs-on: ubuntu-18.04
    container:
      image: archlinux:latest

    steps:
    - name: Install build dependencies
      run: pacman -Sy binutils fakeroot sudo --noconfirm --needed

    - name: Create non-root user that can build the packages
      run: |
        cat /etc/sudoers
        echo 'non_root ALL=NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo
        mkdir /home/non_root
        chown -R non_root:non_root /home/non_root

    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build packages
      run: sudo -u non_root makepkg
    # - name: Get list of packages that have changed
    #   run: find pkg/arch -type f -name "PKGBUILD"