name: publish

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Copy install shell scripts to GitHub Pages branch
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Synchronise shell scripts
      run: |
        SCRIPTS=$(find main/install -type f -name "*.sh")

        for SCRIPT in ${SCRIPTS}
        do
          SUBSCRIPT=$(echo ${SCRIPT} | sed 's/main\/install\///')

          if [ -f "gh-pages/${SCRIPT}" ]; then
            rm "gh-pages/${SCRIPT}"
          fi

          cp "${SCRIPT}" gh-pages
        done

    - name: Deploy new scripts to GitHub Pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        HASH=$(git -C main rev-parse --short HEAD)

        git -C gh-pages add -A
        git -C gh-pages commit -m "Deploy: ${HASH}"
        git -C gh-pages push

  arch-pkg:
    name: Build Arch Linux packages and copy to GitHub Pages branch
    runs-on: ubuntu-18.04
    container:
      image: archlinux:latest

    steps:
    - name: Install build dependencies
      run: makepkg
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    # - name: Get list of packages that have changed
    #   run: find pkg/arch -type f -name "PKGBUILD"