name: publish

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Copy install shell scripts to GitHub Pages branch
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout main branch
      uses: actions/checkout@main
    - name: Copy Install Shell Scripts
      run: ls

  arch-pkg:
    name: Build Arch Linux packages and copy to GitHub Pages branch
    runs-on: ubuntu-18.04
    container:
      image: archlinux:base

    steps:
    - name: Checkout main branch
      uses: actions/checkout@main
    - name: Get list of packages that have changed
      run: ls


# runs:
#   using: docker
#   image: Dockerfile
